version: '3.8'

services:
  # Backend service (Development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flex-living-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - HOSTAWAY_API_URL=${HOSTAWAY_API_URL:-https://api.hostaway.com/v1}
      - HOSTAWAY_ACCOUNT_ID=${HOSTAWAY_ACCOUNT_ID:-61148}
      - HOSTAWAY_API_KEY=${HOSTAWAY_API_KEY:-f94377ebbbb479490bb3ec364649168dc443dda2e4830facaf5de2e74ccc9152}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000,http://localhost:5173}
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - flex-living-network
    restart: unless-stopped

  # Frontend service (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: flex-living-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:3001}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - flex-living-network
    restart: unless-stopped

networks:
  flex-living-network:
    driver: bridge

volumes:
  node_modules:
